### ISSUE TITLE
Warnings appear in log

### ISSUE THREAD

**Issue by booyaa** [lisanet/homebridge-prowl-notification#1]
## Log message

```
[10/5/2022, 19:42:01] [homebridge-prowl-notification] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
```

## System details
- OS: Raspbian
- Homebridge version: v1.5.0
- homebridge-prowl-notification v1.0.0

The plugin works great, but this message is spamming my logs

## Debug enabled logging

```
[10/5/2022, 19:51:34] [homebridge-prowl-notification] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[10/5/2022, 19:51:34] [homebridge-prowl-notification] Error: 
    at On.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at On.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2014:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at ProwlNotification.getState (/usr/lib/node_modules/homebridge-prowl-notification/index.js:130:5)
    at On.emit (events.js:314:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
```

**Comment by CTMULOW** [comment]
Really useful plugin just solved a problem I had with Netatmo's withdrawal of is IFTTT service, but have the same error spamming my logs.

[3/8/2023, 12:06:58 PM] [homebridge-prowl-notification] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[3/8/2023, 12:06:58 PM] [homebridge-prowl-notification] Error: 
    at On.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at On.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2488:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at ProwlNotification.getState (/usr/lib/node_modules/homebridge-prowl-notification/index.js:130:5)
    at On.emit (node:events:513:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
